### Get hotels - 200
POST {{url}}/hotel
Content-Type: application/json

{
  "page": 0,
  "pageSize": 10,
  "filter": "PRICE_LOW_TO_HIGH",
  "filters": {
    "oneStar": false,
    "twoStars": false,
    "threeStars": false,
    "fourStars": true,
    "fiveStars": true,
    "hotelAmenities": [
      "WIFI"
    ],
    "minPrice": 0,
    "maxPrice": 2000,
    "guests": 2,
    "bedrooms": 1,
    "city": "Lille"
  }
}

> {%
    client.test("Check response status", function (){
        client.assert(response.status == 200, "Expected 200, but it was " + response.status)
    })
%}
