services:
  akkorhotel-application:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - PORT=${{ shared.PORT }}
      - MONGO_URI=${{ shared.MONGO_URI }}
      - DATABASE_NAME=${{ shared.DATABASE_NAME }}
      - ALLOWED_ORIGINS=${{ shared.ALLOWED_ORIGINS }}
      - APP_EMAIL=${{ shared.APP_EMAIL }}
      - MAIL_PASSWORD=${{ shared.MAIL_PASSWORD }}
      - MAIL_MODIFIED_USERNAME=${{ shared.MAIL_MODIFIED_USERNAME }}
      - MAIL_REGISTER_SUBJECT=${{ shared.MAIL_REGISTER_SUBJECT }}
      - MAIL_REGISTER_CONFIRMATION_LINK=${{ shared.MAIL_REGISTER_CONFIRMATION_LINK }}
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
