### Delete a Booking - 200
DELETE {{url}}/private/booking/b7a8ff11-314a-47e2-9108-ca4b1a65c592
Content-Type: application/json
Authorization: Bearer {{token}}

> {%
    client.test("Check response status", function (){
        client.assert(response.status == 200, "Expected 200, but it was " + response.status)
    })
%}