springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

spring:
  mail:
    username: username #Value to update
    password: password #Value to update

akkorhotel:
  properties:
    database-name: akkorhotel_local
    allowed-origins: '*'
    mail-modified-username: "[TEST] AkkorHotel"
    mail-register-subject: "[TEST] Confirmez votre inscription à AkkorHotel"
    mail-register-confirmation-link: https://www.example.com/link
    default-user-profile-image: https://i.ibb.co/FbZDPKWx/png-transparent-jedi-avatar-user-profile.png

    mongo-uri: mongoUri #Value to update
    cloudinary-api-key: cloudinaryApiKey #Value to update
    cloudinary-cloud-name: cloudinaryCloudName #Value to update
    cloudinary-api-secret: cloudinaryApiSecret #Value to update