name: CI/CD

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

  pull_request:
    branches:
      - '*'

env:
  IMAGE_NAME: ci-cd
  MAIN_BRANCH: main

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'

      - name: Build & Test
        run: mvn -B verify --file hotel/pom.xml

  CD:
    if: ${{ github.event_name != 'pull_request' }}

    runs-on: ubuntu-latest
    needs: CI

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Build jar file
        run: mvn clean install -DskipTests --file hotel/pom.xml
